### ISSUE TITLE
Where to put effort?

### ISSUE THREAD

**Issue by HEnquist** [ejmahler/RustFFT#16]
I saw the experimental simd release and tried it. It's a really nice improvement over master. Is there any guess of when that will run on stable rust? I'm thinking about what to do in the meanwhile. If that is years away, then it makes sense to continue working on the non-simd version, but if it's reasonably soon then it's better to focus on the simd branch.

Separate question, could we get a 4.1.0 release of the current master? It has become quite a lot faster since 4.0.

**Comment by ejmahler** [comment]
If you're still working on an updated planner, I'd be happy to include that in a 4.1

The biggest hangup for 5.0 is min_specialization. I don't have any hope that that will be stabilized soon.

I see a few options, which I plan to spend the next few weeks thinking about:

1: Wait years until min_specialization is stabilized
2: Find some hack that lets us replace specialization
3: Release AVX support as an opt-in cargo feature - when the feature is disabled, the MSRV is some stable rustc version, and when it's enabled, the MSRV is nightly

As where to direct your focus, I think working on the scalar code is still very important, because there are many users who either work outside of x86_64, or are targeting low-end CPUs like celerons that don't have AVX.

**Comment by ejmahler** [comment]
If option 2 existed, that would be my preferred solution. Option 3 is a good last-ditch choice, but I just know there will be many, many users who never realize they have to opt in.

**Comment by HEnquist** [comment]
Ok! I took a quick look at min_specialization and it looks more like years than months before that can be ready. If it's possible, option 2 seems like the wisest choice. If not, option 3 looks better than 1!

My idea for the new planner is to do it in two steps:
1. Split the planning so if first makes a "recipe" for the FFT, then builds the FFT from the recipe. This makes it easy to write tests that check that it picked the right algorithms. This part is almost finished. In itself it doesn't add any value for the end user (it actually makes the planning take a tiny bit longer), but it's necessary for the next step. And testing is of course good.
2. Make the planner plan several possible recipes, then estimate the processing cost for each one and pick the fastest. My idea here is that it's very difficult to make a set of rules that makes the planner pick the right recipe for every possible case. I'm hoping this can be a more reliable way to get the fastest fft. I have only started looking at how to estimate, there is quite some work left. 

I think it would be good to release 4.1 now. The existing planner is pretty good. I think it only picks the wrong algorithm for quite unusual lengths, and then the one it picks is not terrible.  And I don't know how long it will take until the new planner is actually giving any benefits.

**Comment by ejmahler** [comment]
4.1 is released, and simd is merged into master, so you won't need to worry about straddling two incompatible versions anymore

**Comment by HEnquist** [comment]
Perfect! Closing this issue :)

**Comment by ejmahler** [comment]
Just fyi, if you're still working on planner things, I got AVX working on stable and merged it into master.

I split FftPlanner into two different structs. One is FftPlannerScalar, which explicity opts out of any AVX stuff, and the other is a new enum called FftPlanner, which has the logic for choosing which planner to use.

So if you want to test the scalar planner eithout the AVX planner getting in the way, you can switch over to creating instances of FftPlannerScalar directly.
