### ISSUE TITLE
Fast FFT on wasm32 target

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [ejmahler/RustFFT#89]
Hello,

Do you think it can be realistic to add support of WebAssembly SIMD for this crate ?

Best,
Marc-Antoine

**Comment by ejmahler** [comment]
For every other SIMD setup, we have a feature flag to turn it on/off - if we continued that pattern for wasm, then we could just unconditionally use wasm instructions when the feature flag is on, and tell users to turn it off if they want to target machines that don't have it.

I think that's a pretty disappointing restriction though, hopefully one that gets lifted, so i'd definitely want to architect it so that it *can* be switched over to doing runtime checks if runtime checks become available.

**Comment by HEnquist** [comment]
Maybe by making a placeholder "is_wasm32_feature_detected" macro that always returns true? Then it's a quick fix to switch to a proper such macro if it becomes available. 
The one for x86 is documented [here](https://doc.rust-lang.org/std/macro.is_x86_feature_detected.html#).

**Comment by pr1metine** [comment]
I‘m currently looking into writing a wasm library for generating spectrograms. Because of this, I‘d love to have this feature. What‘s the status of this issue? Ofc I can work on this if nobody else wants to.

**Comment by HEnquist** [comment]
I don't think anyone is working on it.
The speedup from SSE was about 2.5x for f32 and 1.5x for f64. Wasm provides pretty similar functionality so those numbers are probably useful as a rough guess for what can be expected. Would that make a significant difference for your application?

**Comment by pr1metine** [comment]
Yeah, definitely. My users shall be able to „scroll“ through this spectrogram. That would mean that thousands of FFTs may run on every scroll refresh.

**Comment by HEnquist** [comment]
Ok, then perhaps we have a volunteer to work on this 😉
I made the sse and neon implementations so I can (hopefully) answer any questions you may have about those.

**Comment by ejmahler** [comment]
I'd he happy to review+merge a wasm port of our SSE+neon code
