### ISSUE TITLE
Migrate benches to criterion?

### ISSUE THREAD

**Issue by HEnquist** [ejmahler/RustFFT#9]
I have been having trouble getting consistent bench results from the benches in RustFFT. In another project  I use Criterion which is giving better results and can then present them in a much clearer way. It also runs on stable rust. 
Should I migrate the benches to criterion and submit a PR?

**Comment by ejmahler** [comment]
I appreciate criterion for its improved accuracy, but one criticism I have is that it takes significantly longer to get its results, while the built-in benchmarks are less accurate, but you get your results within 15-30 seconds rather than 15-30 minutes. Maybe there's a way to tune criterion to run faster, like reducing the warmup time?

Does criterion have any way to format the results like the built-in bencher? Another point in the built in bencher's favor is that the results are much more compact, with all of your benches usually fitting on one screen.

If there's a way to resolve these 2 issues then I'm open to it.

**Comment by HEnquist** [comment]
Those are good points, I will check if criterion can be used for getting fast and compact results. If not, maybe it's possible to just add a criterion bench suite without removing the existing one.
In any case I will wait with this since I'm busy working on a new version of the planner. There are still cases where it doesn't pick the best algo, and the way it works now it's really tricky to make tests for it.

**Comment by HEnquist** [comment]
I'll look into this and if it works out I will submit a PR.
